name 'heppuppet-argus'
version '0.0.1'

author 'schwicke'
license 'Apache License, Version 2.0 (the "License")'
project_page 'http://www.eu-emi.eu/'
summary 'EMI Argus service'
description 'This modules provides classes and definitions required to setup an Argus server instance.'
dependency 'puppetlabs/stdlib', '>=4.1.0'
dependency 'ripienaar/concat', '>=0.2.0'
dependency 'puppetlabs/firewall', '>=0.3.1'
dependency 'heppuppet/vosupport', '>=0.0.1'
dependency 'heppuppet/lemon', '>=0.0.1'
dependency 'pdxcat/autofs', '>=0.0.2'
